on:
  push:
    tags:
        - 'v*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build
    
    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              
            - name: Publish to npm
              run: bun publish --access public
              env:
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish to github packages
              run: bun publish --registry=https://npm.pkg.github.com
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}